### ISSUE TITLE
Generate Thumbnails does not work in Blender 5.0

### ISSUE THREAD

**Issue by josh-atkins** [gregzaal/Gaffer#177]
**Describe the bug**
"Generate Thumbnails" does not generate thumbnails in Blender 5.0 and produces this error
`AttributeError: 'Scene' object has no attribute 'node_tree'`

**To Reproduce**
1. Download HDRIs from PolyHaven if not already downloaded
2. Open Blender via Terminal to view console errors
3. Go to World > HDRI
4. Click on "Generate Thumbnails"
5. See error

**Expected behavior**
Thumbnails are generated

**Observed behavior**
Blender spends some time working on Gaffer thumbnail generation then resumes normal operation. Thumbnails are not updated. If Blender is opened via Terminal, it looks like all HDRIs are looped through and each produces an error, example console output below.

**Console Output**
```
Blender 5.0.0 (hash a37564c4df7a built 2025-11-18 10:00:50)
/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py:39: DeprecationWarning: 'Scene.use_nodes' is expected to be removed in Blender 6.0
  scene.use_nodes = True
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py", line 40, in <module>
    node_tree = scene.node_tree
                ^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'node_tree'
/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py:39: DeprecationWarning: 'Scene.use_nodes' is expected to be removed in Blender 6.0
  scene.use_nodes = True
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py", line 40, in <module>
    node_tree = scene.node_tree
                ^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'node_tree'

Blender quit
    street_lamp: /Users/user/Desktop/550_LicensedAssetsLibrary/3D/AddonsAndTools/Gaffer/HDRI Haven/street_lamp_1k.hdr  2 MB

Blender quit
    studio_country_hall: /Users/user/Desktop/550_LicensedAssetsLibrary/3D/AddonsAndTools/Gaffer/HDRI Haven/studio_country_hall_1k.hdr  2 MB
/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py:39: DeprecationWarning: 'Scene.use_nodes' is expected to be removed in Blender 6.0
  scene.use_nodes = True
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py", line 40, in <module>
    node_tree = scene.node_tree
                ^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'node_tree'
/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py:39: DeprecationWarning: 'Scene.use_nodes' is expected to be removed in Blender 6.0
  scene.use_nodes = True
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py", line 40, in <module>
    node_tree = scene.node_tree
                ^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'node_tree'
/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py:39: DeprecationWarning: 'Scene.use_nodes' is expected to be removed in Blender 6.0
  scene.use_nodes = True
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py", line 40, in <module>
    node_tree = scene.node_tree
                ^^^^^^^^^^^^^^^
/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py:39: DeprecationWarning: 'Scene.use_nodes' is expected to be removed in Blender 6.0
  scene.use_nodes = True
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py", line 40, in <module>
    node_tree = scene.node_tree
                ^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'node_tree'
AttributeError: 'Scene' object has no attribute 'node_tree'

Blender quit

Blender quit
    studio_garden: /Users/user/Desktop/550_LicensedAssetsLibrary/3D/AddonsAndTools/Gaffer/HDRI Haven/studio_garden_1k.hdr  2 MB
/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py:39: DeprecationWarning: 'Scene.use_nodes' is expected to be removed in Blender 6.0
  scene.use_nodes = True
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py", line 40, in <module>
    node_tree = scene.node_tree
                ^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'node_tree'
/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py:39: DeprecationWarning: 'Scene.use_nodes' is expected to be removed in Blender 6.0
  scene.use_nodes = True
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Blender/5.0/scripts/addons/Gaffer/resize.py", line 40, in <module>
    node_tree = scene.node_tree
                ^^^^^^^^^^^^^^^
AttributeError: 'Scene' object has no attribute 'node_tree'
    studio_kominka_01: /Users/user/Desktop/550_LicensedAssetsLibrary/3D/AddonsAndTools/Gaffer/HDRI Haven/studio_kominka_01_1k.hdr  2 MB

Blender quit

Blender quit
    studio_kominka_02: /Users/user/Desktop/550_LicensedAssetsLibrary/3D/AddonsAndTools/Gaffer/HDRI Haven/studio_kominka_02_1k.hdr  2 MB

Blender quit

Blender quit
    studio_kominka_03: /Users/user/Desktop/550_LicensedAssetsLibrary/3D/AddonsAndTools/Gaffer/HDRI Haven/studio_kominka_03_1k.hdr  2 MB
    studio_kominka_04: /Users/user/Desktop/550_LicensedAssetsLibrary/3D/AddonsAndTools/Gaffer/HDRI Haven/studio_kominka_04_1k.hdr  2 MB
    studio_kontrast_01: /Users/user/Desktop/550_LicensedAssetsLibrary/3D/AddonsAndTools/Gaffer/HDRI Haven/studio_kontrast_01_1k.hdr  2 MB
```

**Desktop (please complete the following information):**
 - OS: macOS 15.6.1 (24G90)
 - Blender Version 5.0.0
 - Gaffer Version 3.2.7

**Comment by gregzaal** [comment]
Thanks for the report, fixed in v3.2.8 (bb9602ff).

**Comment by josh-atkins** [comment]
Thanks @gregzaal , I have the same output as @michaelrampl on v3.2.8, and actually noticed it on Blender startup too.
I.e. steps:

1. Open Blender
2. Generate thumbnails
3. Close Blender and Reopen
4. Console output has `Missing thumb [name of HDRI]` for every HDRI

When I open the HDRI browser there is also a short pause where the addon seems to be searching for the thumb files (i.e. grey buffering image), then reverts to the pink "thumbnail missing" placeholder.

Thanks - let me know if you want any more diagnostics!
