### ISSUE TITLE
Not working in 2.8. - Changes in outliner?

### ISSUE THREAD

**Issue by Idur73** [gregzaal/Gaffer#108]
Hello Greg,

I don´t know if you  already know, but Gaffer is not working with a newer version of 2.8. 
If think the reason is that they changed a lot in the outline in the last days. 

All the best
Clemens

**Comment by gregzaal** [comment]
I didn't know, thanks. Can you show me the error it produces?

**Comment by Idur73** [comment]
Here we go:
Traceback (most recent call last):
  File "C:\Users\Idur.DESKTOP-LN37EKA\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Gaffer-trial\ui.py", line 643, in draw
    draw_cycles_UI(context, layout, lights)
  File "C:\Users\Idur.DESKTOP-LN37EKA\AppData\Roaming\Blender Foundation\Blender\2.80\scripts\addons\Gaffer-trial\ui.py", line 114, in draw_cycles_UI
    if (gaf_props.VisibleLightsOnly and not a.hide_viewport) or (not gaf_props.VisibleLightsOnly):
AttributeError: 'Object' object has no attribute 'hide_viewport'

**Comment by gregzaal** [comment]
From the latest blender developer meeting notes:

> We aim to freeze the 2.80 user interface and Python API this week, so it
is stable for documentation and add-ons. So far things are going according
to plan, but we will evaluate next Monday if everything is in place.

So I'm going to wait until at least next week before fixing this, chances are there will be more changes.

**Comment by gregzaal** [comment]
Just tested in a recent build, it seems objects do still have the `hide_viewport` property so everything works fine.

Not sure if they removed this and then added it back again later, or you were using an older version without it.

Either way, it works in the latest version of blender 2.8 :)
